### ISSUE TITLE
Only showing test ads

### ISSUE THREAD

**Issue by dheerajbred** [EPNW/unity_ads_flutter#2]
My placements are working and live but in here only test ads are showing up. 

Any suggestion to fix this is appreciated

Thanks

**Comment by EstebanErcole** [comment]
Hi @dheerajbred , have you been able to solve it?

**Comment by EP-u-NW** [comment]
Hi,
which platform (Android/iOS) are you testing? Are you running your app in production or debug mode?

**Comment by dheerajbred** [comment]
Hi, the problem is solved. It was just a low fill rate. Thank you.
